config/routes.rb
Rails.application.routes.draw do

  authenticated :user, -> user { user.admin? } do 
    mount Delayed::Web::Engine, at: '/jobs'
  end
  
  get 'auth/:provider/callback', to: 'connections#create'
  resources :connections, only: [:destroy]
  get 'auth/failure', to: 'connections#omniauth_failure'

  devise_for :users, controllers: {registrations: 'registrations'}
  root 'pages#home'
  get 'dashboard', to: "pages#dashboard"

  resources :posts do 
    member do 
      put :cancel
    end
  end

end

app/models/connection.rb
class Connection < ActiveRecord::Base
	belongs_to :user

	def self.create_from_omniauth(auth_hash)
		create(
		provider: auth_hash.provider,
		oauth_token: auth_hash.credentials.token,
		secret: auth_hash.credentials.secret
		)
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :content
	validates_presence_of :scheduled_at
	validates_length_of :content, maximum: 140, message: "less than 140 please"
	validates_datetime :scheduled_at, :on => :create, :on_or_after => Time.zone.now
	after_create :schedule

	def schedule
		begin
			ScheduleJob.set(wait_until: scheduled_at).perform_later(self)
			self.update_attributes(state: "scheduled")
		rescue Exception => e
			self.update_attributes(state: "scheduling error", error: e.message)
		end
	end

	def display
		begin
			unless state == "canceled"
				if facebook == true
					to_facebook
				end
				if twitter == true
					to_twitter
				end
			end
			self.update_attributes(state: "posted")
		rescue Exception => e
			self.update_attributes(state: "posting error", error: e.message)
		end
	end

	def to_twitter
		client = Twitter::REST::Client.new do |config|
			config.access_token = self.user.twitter.oauth_token
			config.access_token_secret = self.user.twitter.secret
			config.consumer_key = ENV['TWITTER_KEY']
			config.consumer_secret = ENV['TWITTER_SECRET']
		end
		client.update(self.content)
	end

	def to_facebook
		graph = Koala::Facebook::API.new(self.user.facebook.oauth_token)
		graph.put_connections("me", "feed", message: self.content)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   validates_presence_of :time_zone

   has_many :connections, dependent: :destroy
   has_many :posts, dependent: :destroy

   def facebook
   	self.connections.where(provider: "facebook").first
   end

   def twitter
   	self.connections.where(provider: "twitter").first
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  around_filter :user_time_zone, if: :current_user

  private

  def user_time_zone(&block)
  	Time.use_zone(current_user.time_zone, &block)
  end

end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
	before_action :set_connection, only: [:destroy]

  def create
  	connection = current_user.connections.create_from_omniauth(auth_hash)
  	if connection.save
  		redirect_to dashboard_path, notice: "Connection created!"
  	else
  		redirect_to dashboard_path, notice: "Something went wrong"
  	end
  end

  def destroy
  	@connection.destroy
  	redirect_to dashboard_path, notice: "Connection deleted"
  end

  def omniauth_failure
    redirect_to to dashboard_path, notice: "Something went wrong"
  end

  private

  def set_connection
  	@connection = Connection.find(params[:id])
  end

  def auth_hash
  	request.env['omniauth.auth']
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user!, only: [:dashboard]
  def home
  	if current_user
  		redirect_to dashboard_path
  	end
  end

  def dashboard
  	@scheduled = current_user.posts.where(state: "scheduled").paginate(page: params[:scheduled_page], per_page: 4).order('scheduled_at ASC')
  	@history = current_user.posts.where.not(state: "scheduled").paginate(page: params[:history_page], per_page: 4).order('scheduled_at DESC')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:cancel]

	def new
		if current_user.connections.any?
			@post = Post.new
		else
			redirect_to dashboard_path, notice: "Please connect to a social network first"
		end
	end

	def create
		@post = current_user.posts.new(post_params)

		respond_to do |format|
			if @post.save
				format.html {redirect_to dashboard_path, notice: "Post was successfully created."}
			else
				format.html { render :new }
			end
		end
	end

	def cancel
		@post.update_attributes(state: "canceled")
		redirect_to dashboard_path, notice: "Post was successfully canceled"
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:content, :scheduled_at, :state, :user_id, :facebook, :twitter)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	private

	def sign_up_params
		params.require(:user).permit(:email, :password, :time_zone)
	end

	def account_update_params
		params.require(:user).permit(:email, :password, :time_zone, :current_password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Stuker", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li><%= link_to "New Post", new_post_path %></li>
        <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Settings", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stuker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>
	<% flash.each do |type, message| %>
	<div class="alert alert-info fade-in">
		<button class="close" data-dismiss="alert">x</button>
		<%= message %>
	</div>
	<% end %>
	<div class="container">

	

	<%= yield %>
	</div>
</body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">

<!-- Profile and Connections -->
<div class="col-md-2 text-center">
<%= image_tag "stuker.jpg", class: "logo" %>
<hr>
<div class="timezone">
<p class="text-center"><b><%= Time.zone.name %> Timezone</b></p>
<%= link_to "change", edit_user_registration_path %>
</div>
<hr>
<div class="social">
<% unless current_user.connections.where(provider: "twitter").any? %>
<%= link_to "Connect with Twitter", "/auth/twitter", class: "btn btn-info btn-block btn-sm" %>
<% else %>
<%= link_to "Connect with Twitter", "/auth/twitter", class: "btn btn-info btn-block btn-sm", disabled: true %>
<%= link_to "Delete Connection", connection_path(current_user.connections.where(provider: "twitter").first), method: :delete %>
<% end %>

<% unless current_user.connections.where(provider: "facebook").any? %>
<%= link_to "Connect with Facebook", "/auth/facebook", class: "btn btn-primary btn-block btn-sm" %>
<% else %>
<%= link_to "Connect with Facebook", "/auth/facebook", class: "btn btn-primary btn-block btn-sm", disabled: true %>
<%= link_to "Delete Connection", connection_path(current_user.connections.where(provider: "facebook").first), method: :delete %>
<% end %>
</div>
</div>

<!-- New Post and Scheduled -->

<div class="col-md-5">
<h3 class="text-center">Scheduled Posts</h3>
<hr>
<%= render @scheduled %>
<%= will_paginate @scheduled, :param_name => 'scheduled_page' %>
</div>

<!-- History -->

<div class="col-md-5">
<h3 class="text-center">Post History</h3>
<hr>
<%= render @history %>
<%= will_paginate @history, :param_name => 'history_page' %>
</div>
</div>

app/views/pages/home.html.erb
<div class="text-center landing_title">
<%= link_to "The Freedom to Post", new_user_session_path, class: "btn btn-default btn-lg btn-landing" %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
<%= f.input :content, required: true, maxlength: 140 %>
<p>This post will be scheduled in <b><%= Time.zone.name %></b> time</p>
<%= f.input :scheduled_at, required: true, as: :datetime_picker %>
</div>

<div class="form-inputs">
	<% if current_user.connections.where(provider: "facebook").any? %>
	<%= f.input :facebook %>
	<% end %>
	<% if current_user.connections.where(provider: "twitter").any? %>
	<%= f.input :twitter %>
	<% end %>
</div>

<div class="form-actions">
<%= f.button :submit %>
</div>

<% end %>

app/views/posts/_post.html.erb
<div class="panel panel-default">
<div class="panel-heading">
<% if post.facebook == true %><span class="label label-primary">Facebook</span><% end %>
<% if post.twitter == true %><span class="label label-info">Twitter</span><% end %>
Scheduled on <%= post.scheduled_at %>
</div>
<div class="panel-body">
<%= post.content %>
</div>
<div class="panel-footer">
<p><%= post.state.capitalize %></p>
<%= link_to "Cancel", cancel_post_path(post), method: :put if post.state == "scheduled" %>
</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render "form" %>
<%= link_to "Back", dashboard_path %>